import {
  Agency,
  Cylinder,
  CylinderType,
  Delivery,
  Godown,
  Invoice,
  Order,
  PlantDashboardStats,
} from "@/types/erp";

/**
 * MOCK / DEMO DATASET
 * All entities, quantities, weights, rates, vehicle plates, and names below
 * are fictional illustrative placeholders designed for UI evaluation.
 * They do not reflect real client data or active operational records.
 */

export const MOCK_CYLINDER_TYPES: CylinderType[] = [
  {
    id: "cyl-142",
    code: "14.2kg",
    name: "14.2 KG Domestic Refill (Sample Spec)",
    category: "DOMESTIC",
    tareWeightKg: 15.3,
    gasWeightKg: 14.2,
    grossWeightKg: 29.5,
    basePrice: 850.0,
    gstRate: 5.0, // Sample 5% GST illustration
    depositAmount: 1450,
  },
  {
    id: "cyl-190",
    code: "19kg",
    name: "19.0 KG Commercial Cylinder (Sample Spec)",
    category: "COMMERCIAL",
    tareWeightKg: 19.8,
    gasWeightKg: 19.0,
    grossWeightKg: 38.8,
    basePrice: 1750.0,
    gstRate: 18.0, // Sample 18% GST illustration
    depositAmount: 2500,
  },
  {
    id: "cyl-475",
    code: "47.5kg",
    name: "47.5 KG Industrial Manifold (Sample Spec)",
    category: "INDUSTRIAL",
    tareWeightKg: 42.5,
    gasWeightKg: 47.5,
    grossWeightKg: 90.0,
    basePrice: 4200.0,
    gstRate: 18.0,
    depositAmount: 6000,
  },
  {
    id: "cyl-050",
    code: "5kg",
    name: "5.0 KG Portable Domestic (Sample Spec)",
    category: "DOMESTIC",
    tareWeightKg: 6.2,
    gasWeightKg: 5.0,
    grossWeightKg: 11.2,
    basePrice: 340.0,
    gstRate: 5.0,
    depositAmount: 800,
  },
];

export const MOCK_DASHBOARD_STATS: PlantDashboardStats = {
  todayOrdersCount: 842,
  todayOrdersChangePct: 14.2,
  pendingDeliveriesCount: 38,
  filledStockTotal: 4820,
  emptyStockTotal: 1940,
  underTestingCount: 164,
  outstandingDuesFormatted: "₹ 4,85,200 (Sample)",
  monthlySalesFormatted: "₹ 86,42,800 (Sample)",
  cylindersInTransit: 980,
  activeAgenciesCount: 24,
};

export const MOCK_GODOWNS: Godown[] = [
  {
    id: "g-01",
    name: "Central Bottling & Decanting Godown (Sample)",
    code: "GD-PLANT-01",
    location: "Main Plant Campus (Sample Sector)",
    capacityMax: 8000,
    currentFilledStock: {
      "14.2kg": 3200,
      "19kg": 1150,
      "47.5kg": 340,
      "5kg": 130,
    },
    currentEmptyStock: {
      "14.2kg": 1200,
      "19kg": 520,
      "47.5kg": 140,
      "5kg": 80,
    },
    supervisorName: "Plant Supervisor A (Sample)",
    supervisorPhone: "+91 (Sample Phone)",
  },
  {
    id: "g-02",
    name: "City Distribution Depot (Sample)",
    code: "GD-SOUTH-02",
    location: "Logistics Corridor Depot (Sample)",
    capacityMax: 3500,
    currentFilledStock: {
      "14.2kg": 1100,
      "19kg": 420,
      "47.5kg": 90,
      "5kg": 40,
    },
    currentEmptyStock: {
      "14.2kg": 410,
      "19kg": 190,
      "47.5kg": 35,
      "5kg": 20,
    },
    supervisorName: "Plant Supervisor B (Sample)",
    supervisorPhone: "+91 (Sample Phone)",
  },
];

export const MOCK_AGENCIES: Agency[] = [
  {
    id: "ag-01",
    code: "AG-DEMO-01",
    name: "Apex Gas Distributors (Demo Agency)",
    proprietor: "Sample Proprietor A",
    gstin: "27SAMPLE0000A1Z5",
    phone: "+91 (Demo Agency Phone)",
    email: "agency01@sample-lpg.demo",
    address: "Sample Commercial Corridor, Zone 1",
    territory: "North Distribution Sector (Sample)",
    securityDeposit: 500000,
    creditLimit: 750000,
    currentOutstanding: 142800,
    cylindersInCirculation: {
      "14.2kg": 3450,
      "19kg": 480,
      "47.5kg": 60,
      "5kg": 120,
    },
    status: "ACTIVE",
    joinedDate: "2024-01-01",
  },
  {
    id: "ag-02",
    code: "AG-DEMO-02",
    name: "Green Flame Energy (Demo Agency)",
    proprietor: "Sample Proprietor B",
    gstin: "27SAMPLE0000A1Z5",
    phone: "+91 (Demo Agency Phone)",
    email: "agency02@sample-lpg.demo",
    address: "Industrial Complex Gateway, Zone 2",
    territory: "Central Commercial Belt (Sample)",
    securityDeposit: 600000,
    creditLimit: 900000,
    currentOutstanding: 215400,
    cylindersInCirculation: {
      "14.2kg": 2100,
      "19kg": 1240,
      "47.5kg": 180,
      "5kg": 90,
    },
    status: "ACTIVE",
    joinedDate: "2024-02-15",
  },
  {
    id: "ag-03",
    code: "AG-DEMO-03",
    name: "Metro LPG Services (Demo Agency)",
    proprietor: "Sample Proprietor C",
    gstin: "27SAMPLE0000A1Z5",
    phone: "+91 (Demo Agency Phone)",
    email: "agency03@sample-lpg.demo",
    address: "Transit Terminal Hub, Zone 3",
    territory: "South Urban Cluster (Sample)",
    securityDeposit: 400000,
    creditLimit: 500000,
    currentOutstanding: 68000,
    cylindersInCirculation: {
      "14.2kg": 4200,
      "19kg": 310,
      "47.5kg": 25,
      "5kg": 220,
    },
    status: "ACTIVE",
    joinedDate: "2024-03-10",
  },
  {
    id: "ag-04",
    code: "AG-DEMO-04",
    name: "Royal Flame Commercial (Demo Agency)",
    proprietor: "Sample Proprietor D",
    gstin: "27SAMPLE0000A1Z5",
    phone: "+91 (Demo Agency Phone)",
    email: "agency04@sample-lpg.demo",
    address: "Hospitality & Restaurant Zone (Sample)",
    territory: "Commercial Manifold Cluster (Sample)",
    securityDeposit: 800000,
    creditLimit: 1200000,
    currentOutstanding: 59000,
    cylindersInCirculation: {
      "14.2kg": 850,
      "19kg": 2200,
      "47.5kg": 340,
      "5kg": 40,
    },
    status: "ACTIVE",
    joinedDate: "2024-04-01",
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-8021",
    orderNumber: "ORD-DEMO-0842",
    orderDate: "Today (Demo Time)",
    customerType: "AGENCY",
    entityId: "ag-01",
    entityName: "Apex Gas Distributors (Demo)",
    status: "IN_TRANSIT",
    items: [
      {
        cylinderType: "14.2kg",
        quantity: 300,
        unitPrice: 850,
        taxableAmount: 255000,
        gstAmount: 12750,
        totalAmount: 267750,
        emptiesReturnedExpected: 300,
        emptiesReceivedActual: 300,
      },
      {
        cylinderType: "19kg",
        quantity: 50,
        unitPrice: 1750,
        taxableAmount: 87500,
        gstAmount: 15750,
        totalAmount: 103250,
        emptiesReturnedExpected: 50,
      },
    ],
    totalQuantity: 350,
    totalTaxable: 342500,
    totalGst: 28500,
    grandTotal: 371000,
    paymentStatus: "PARTIAL",
    deliveryVehicle: "VEHICLE-DEMO-01 (Sample Truck)",
    driverName: "Driver 01 (Sample)",
    scheduledDeliveryDate: "Scheduled Slot (Sample)",
  },
  {
    id: "ord-8020",
    orderNumber: "ORD-DEMO-0841",
    orderDate: "Today (Demo Time)",
    customerType: "AGENCY",
    entityId: "ag-02",
    entityName: "Green Flame Energy (Demo)",
    status: "ALLOCATED",
    items: [
      {
        cylinderType: "19kg",
        quantity: 120,
        unitPrice: 1750,
        taxableAmount: 210000,
        gstAmount: 37800,
        totalAmount: 247800,
        emptiesReturnedExpected: 120,
      },
    ],
    totalQuantity: 120,
    totalTaxable: 210000,
    totalGst: 37800,
    grandTotal: 247800,
    paymentStatus: "PENDING",
    deliveryVehicle: "VEHICLE-DEMO-02 (Sample Truck)",
    driverName: "Driver 02 (Sample)",
    scheduledDeliveryDate: "Scheduled Slot (Sample)",
  },
];

export const MOCK_CYLINDERS: Cylinder[] = [
  {
    serialNumber: "CYL-DEMO-2024-001",
    barcode: "SAMPLE890123456",
    typeId: "cyl-142",
    cylinderType: "14.2kg",
    status: "FILLED",
    manufacturingDate: "2022-03 (Sample)",
    lastTestedDate: "2022-03 (Sample)",
    nextTestDueDate: "2027-03 (Sample)",
    currentGodownId: "g-01",
    tareWeightActual: 15.28,
    grossWeightActual: 29.48,
    qrPayload: "LPGF-CYL-DEMO-001",
  },
  {
    serialNumber: "CYL-DEMO-2023-002",
    barcode: "SAMPLE890123789",
    typeId: "cyl-190",
    cylinderType: "19kg",
    status: "OUT_FOR_DELIVERY",
    manufacturingDate: "2021-08 (Sample)",
    lastTestedDate: "2021-08 (Sample)",
    nextTestDueDate: "2026-08 (Sample)",
    currentVehicleId: "VEHICLE-DEMO-01",
    assignedAgencyId: "ag-01",
    tareWeightActual: 19.82,
    grossWeightActual: 38.82,
    qrPayload: "LPGF-CYL-DEMO-002",
  },
];

export const MOCK_DELIVERIES: Delivery[] = [
  {
    id: "del-401",
    tripNumber: "TRIP-DEMO-01",
    vehicleNumber: "VEHICLE-DEMO-01 (Sample Truck)",
    driverName: "Driver 01 (Sample)",
    driverPhone: "+91 (Sample Phone)",
    status: "DISPATCHED",
    startTime: "Sample Schedule Slot",
    cylindersLoaded: {
      filled: { "14.2kg": 300, "19kg": 50, "47.5kg": 0, "5kg": 0 },
      emptyReturned: { "14.2kg": 0, "19kg": 0, "47.5kg": 0, "5kg": 0 },
    },
    destinationAgencies: ["Apex Gas Distributors (Demo)", "Transit Depot (Sample)"],
    stopsCount: 3,
    completedStops: 1,
    routeTitle: "Corridor Route 01 (Illustrative Sample)",
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv-demo-1042",
    invoiceNumber: "INV/DEMO/01042",
    invoiceDate: "Sample Date",
    dueDate: "Sample Due Date",
    orderNumber: "ORD-DEMO-0842",
    recipientName: "Apex Gas Distributors (Demo Agency)",
    recipientGstin: "27SAMPLE0000A1Z5",
    recipientAddress: "Sample Commercial Corridor, Zone 1",
    placeOfSupply: "Sample State Code (Configurable)",
    hsnCode: "27111900 (Sample HSN)",
    cylinderType: "14.2kg",
    quantity: 300,
    unitPrice: 850.0,
    taxableAmount: 255000.0,
    cgstRate: 2.5,
    cgstAmount: 6375.0,
    sgstRate: 2.5,
    sgstAmount: 6375.0,
    totalGstAmount: 12750.0,
    grandTotal: 267750.0,
    status: "PAID",
    irnNumber: "(Sample E-Invoice IRN Placeholder)",
    qrCodeMock: "SAMPLE-DEMO-IRN-QR-DATA",
  },
];
